from config_variables import CONFIG_PLATFORM_VERSION, CONFIG_DEVICE_NAME, CONFIG_APPIUM_SERVER_URL

PLATFORM_NAME = 'iOS'
PLATFORM_VERSION = CONFIG_PLATFORM_VERSION
DEVICE_NAME = CONFIG_DEVICE_NAME
AUTOMATION_NAME = 'XCUITest'
APP_PACKAGE = 'fi.fmi.mobileweather'

APPIUM_SERVER = CONFIG_APPIUM_SERVER_URL
APPIUM_BASE_PATH_START_CMD = 'appium --base-path /wd/hub/'
