name: iOS Robot Framework CI / CD Tests

on:
  workflow_dispatch:

jobs:
  clone-repository:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install robotframework-seleniumlibrary
          
      # Step 4: Install Appium
      - name: Install Appium
        run: |
          npm install -g appium
          npm install -g appium-doctor
          appium-doctor --ios # Check Appium setup

      # Step 5: Clone repository
      - name: Clone Weather App Repository
        run: |
          git clone https://github.com/fmidev/weather-app.git
#          cd weather-app/ios
          echo "Repository cloned successfully"

      # Step 6: Install Yarn
      - name: Install Yarn
        run: yarn install

      # Step 7: Install Pods
      - name: Install Pods
        run: pod install
        working-directory: ios

      # Step 8: Get defaultConfig
      - name: Get defaultConfig
        env:
          defaultConfig: ${{ secrets.DEFAULTCONFIG }}
        shell: bash
        run: |
          touch defaultConfig.ts
          echo "$defaultConfig" >> defaultConfig.ts
